//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakDownV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceID { get; set; }
        public int OilID { get; set; }
        public int BrakesID { get; set; }
        public int TuneUpID { get; set; }
        public int VehicleID { get; set; }
    
        public virtual Brake Brake { get; set; }
        public virtual Oil Oil { get; set; }
        public virtual TuneUp TuneUp { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
